name: CI

on:
  push:
    paths:
      - 'Assets/**'
      - 'Packages/**'
      - 'ProjectSettings/**'
  workflow_dispatch: {}

jobs:
  build:
    name: ${{ matrix.target-platform }}
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: VideoGameCi/Library
          key: Library-${{ matrix.unity-version }}-${{ matrix.target-platform }}
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
          UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
        with:
          targetPlatform: ${{ matrix.target-platform }}
          projectPath: VideoGameCi
          unityVersion: ${{ matrix.unity-version }}
          buildName: VideoGameCi
      - uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.target-platform }}-${{ matrix.unity-version }}
          path: build/${{ matrix.target-platform }}
    strategy:
      matrix:
        unity-version:
          - 2022.1.23f1
        os:
          - windows-2019
          - macos-12
          - ubuntu-latest
        include:
          - os: windows-2019
            target-platform: StandaloneWindows64
          - os: macos-12
            target-platform: StandaloneOSX
          - os: ubuntu-latest
            target-platform: StandaloneLinux64
